# Generated by Django 4.1.4 on 2022-12-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0002_rename_name_element_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('version', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('refbook', 'version')},
        ),
    ]
