# Generated by Django 4.1.4 on 2022-12-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0003_alter_version_version_alter_element_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
