# Generated by Django 4.1.4 on 2022-12-20 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0004_alter_element_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 19, 20, 23, 11847), unique=True),
        ),
    ]
