# Generated by Django 4.1.4 on 2022-12-20 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0005_alter_version_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
