# Generated by Django 4.1.4 on 2022-12-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0006_alter_version_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('refbook', 'version', 'start_date'), ('refbook', 'version')},
        ),
    ]
