# Generated by Django 4.1.4 on 2022-12-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0007_alter_version_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('refbook', 'start_date'), ('refbook', 'version')},
        ),
    ]
